# Generated by Django 5.0.2 on 2024-02-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
    ]
