# Generated by Django 5.0.2 on 2024-02-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('category', models.CharField(max_length=250, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='news_image', verbose_name='Картинка')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Популярное',
                'verbose_name_plural': 'Популярные',
            },
        ),
    ]
