# Generated by Django 5.0.2 on 2024-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Popular_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='popular_image_image', verbose_name='Картинка')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
        ),
    ]
