# Generated by Django 5.0.2 on 2024-02-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='music_style_image', verbose_name='Картинка')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Музыкальная новость',
                'verbose_name_plural': 'Музыкальные новости',
            },
        ),
    ]
